<?php 

const SAMPLE_INFO_CONFIG_KEY = 'sample_info.settings';
const SAMPLE_INFO_DEFAULT_FORMAT = 'full_html';

/**
 * Implements hook_theme().
 */
function sample_info_theme()
{
  return [
    'sample_info_view' => [
      'variables' => [
        'info_text' => NULL,
        'info_integer' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function sample_info_preprocess_html(&$variables)
{
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && $node->bundle()) {
    $variables['attributes']['class'][] = "content-type--{$node->bundle()}";
  }
}